version: '3'

services:

  api-server:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    ports:
      - '7004:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "s@user2023"
      MSSQL_PID: Express
    ports:
      - "1433:1433"

networks:
  app-network:
    driver: bridge
