version: '3'

services:

  Api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - '7004:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
